### ISSUE TITLE
What is a simple code example using uarray that demonstrates "replatforming SciPy"?

### ISSUE THREAD

**Issue by hameerabbasi** [Quansight-Labs/uarray#100]
Can the simple example be used to illustrate:
* dispatch to an optimized implementation
* "symbolic numpy"
* implementation over `getitem` and `iterate`

**Comment by hameerabbasi** [comment]
Here's my take on it:

```python
import uarray as ua
import uarray.numpy as np
import uarray.scipy.linalg as spl


# Create array `x` in TensorFlow/PyTorch/Dask/CuPy

a, b, c = spl.svd(x)

# a, b, c is a TensorFlow graph/CuPy array/whatever

with ua.use_graph(True): # Other options are False and None
    # a, b, c are graphs
    a, b, c = spl.svd(x)

# a, b, c are arrays

# Backends

# Can be used as context manager or to set default
with ua.use_backend(ua.backends.PyTorch, coerce=True):
    # Everything here will use PyTorch and coerce all arrays.

with ua.use_backend(ua.backends.PyTorch, ua.backends.NumPy):
   # Attempts to use PyTorch, and failing that, NumPy

with ua.use_backend(ua.backends.PyTorch, ua.backends.NumPy, coerce=ua.backends.PyTorch):
    # When multiple backends are specified, you must specify the one to coerce to on failure of type check.

```

**Comment by teoliphant** [comment]
```
# Create array `x` in TensorFlow/PyTorch/Dask/CuPy

a, b, c = spl.svd(x)

# a, b, c is a TensorFlow graph/CuPy array/whatever

with ua.use_graph(True): # Other options are False and None
    # a, b, c are graphs
    a, b, c = spl.svd(x)

# a, b, c are arrays

# Backends

# Can be used as context manager or to set default
with ua.use_backend(ua.backends.PyTorch, coerce=True):
    # Everything here will use PyTorch and coerce all arrays.

with ua.use_backend(ua.backends.PyTorch, ua.backends.NumPy):
   # Attempts to use PyTorch, and failing that, NumPy

with ua.use_backend(ua.backends.PyTorch, ua.backends.NumPy, coerce=ua.backends.PyTorch):
    # When multiple backends are specified, you must specify the one to coerce to on failure of type check.
```

**Comment by teoliphant** [comment]
Yes, this is what the API should look like.  This is what we need.

**Comment by ashwinvis** [comment]
@hameerabbasi Thank you for that simple example demonstrating the vision... I believe it is already outdated now that `unumpy` is a separate package. Some documentation would be nice for outsiders to understand what is working now and what's on the roadmap.

**Comment by hameerabbasi** [comment]
@ashwinvis For now I have this simple notebook up. I've attempted to get most `ufunc`s and `ufunc`-related reductions (`sum`, `prod`, `any`, `all`, `min`, `max`) working so far with Xnd, PyTorch and NumPy.

You can take a look at https://github.com/Quansight-Labs/uarray/blob/master/unumpy/tests/test_numpy.py to see what's supported so far, as far as the user-facing API goes.

As far as the dev-facing API, here's a notebook demonstrating it: https://nbviewer.jupyter.org/github/Quansight-Labs/uarray/blob/master/notebooks/basic_tutorial.ipynb

I do plan to write docs once I have enough of the API implemented.

**Comment by hameerabbasi** [comment]
Docs are up at https://uarray.readthedocs.io/en/latest/
