### ISSUE TITLE
Get NumPy ufuncs and reductions working.

### ISSUE THREAD

**Issue by dcharbon** [Quansight-Labs/uarray#114]
- [x] ufuncs
- [x] ufunc-reductions: `sum`, `prod`, `min`, `max`, `any`, `all`
- [x] Other aggregate-reductions (`argmax`/`argmin`)
- [x] `std`/`var`
- [x] NaN-reductions `nan{min,max,prod,sum}`

**Comment by hameerabbasi** [comment]
This is now done.
