### ISSUE TITLE
Decide on API pattern for svd and lu

### ISSUE THREAD

**Issue by dcharbon** [Quansight-Labs/uarray#116]
Many implementations return two matrices. However, lapack and blas return a single matrix. We need to choose a primary function definition that returns either one or two matrixes, and an alternative function definition that returns the alternative and is implemented by default using the primary implementation.

**Comment by dcharbon** [comment]
There are advantages of storage efficiency to be balanced with issues of developer expectations and API usability.

**Comment by hameerabbasi** [comment]
For LAPACK wrappers, there will be a single matrix, and this will be wrapped by the SciPy API.
