### ISSUE TITLE
Collect user stories

### ISSUE THREAD

**Issue by dcharbon** [Quansight-Labs/uarray#132]
@mpeaton will put together a small program using numpy for use in demonstrating uarray combined with MoA. Perhaps an example use of gradient descent? Another possibility, matrix multiplication with taking the diagonal of the result. Ultimately, a use case where it isn't necessary to compute the entire result to generate the desired result. Also, anything that generally requires composability where composability doesn't require the generation of temporary values under MoA.

**Comment by rgommers** [comment]
Another goal: show working examples for uarray backends (more than a toy example, something like gradient descent).

Clarification on the description: there are two separate topics here,

1. show real-world uarray examples
2. show potential of metaldsl + moa

**Comment by alimanfoo** [comment]
Hi folks, apologies if this is not the right place, but I recently heard about uarray via @rgommers PyData talk, and have a use case for something like this. 

I'm in the middle of rewriting a domain-specific package for working with genomic data, and I'd like to write it in a way that has a separation between end-user API and multiple backend implementations, with at least numpy and dask backends implemented to start with but allowing for other backends to be developed and registered.

I think my use case needs more than the ``__array_function__`` protocol, and so some mechanism for explicitly declaring API functions and their implementations would be very useful.

I have currently got my own very simple dispatch mechanism implemented, but would be happy to use something else. Here is the current state of the code: https://github.com/scikit-allel/skallel-tensor/tree/master/src/skallel_tensor

I've skimmed through the `uarray` docs and it looks like the right tool, but there is quite a lot of indirection and I'm struggling a bit to understand how I would use it. In any case, if it would be at all useful to have a use case to consider, then please feel free to follow up.

**Comment by rgommers** [comment]
Hi @alimanfoo, sounds like an interesting use case. I'll have a look at your code later. Quick reply for now: yes we'd like to make the docs clearer. @hameerabbasi just wrote a blog post that could perhaps be helpful: https://labs.quansight.org/blog/2019/07/uarray-update-api-changes-overhead-and-comparison-to-__array_function__/

**Comment by alimanfoo** [comment]
Thanks @rgommers. The blog post is very useful, I think uarray is close to what I'm after. It is probably lack of sleep but I am still struggling to grok the API. I think what I want is also close to Julia's multiple dispatch mechanism, and I've stumbled on a couple of Python implementations, e.g. @mrocklin's [multipledispatch](https://github.com/mrocklin/multipledispatch). Multiple dispatch is easier to grok and to use, but I get that uarray is trying to do more than just multiple dispatch. I'm currently trying to figure out if using multiple dispatch is the best approach for my use case, or if uarray provides some additional benefits that are worth the extra complexity.

FWIW I'm creating a package which provides a set of domain-specific functions that operate on array-like objects. For generality, call my package `foo`, and say that it exposes a function `foo.bar(a)` to the user. Under the hood there might be a `foo.numpy_backend.bar(a)` function which accepts a numpy array, and a `foo.dask_backend.bar(a)` function which accepts a dask array.

For 99.9% of users I don't want them to have to worry about any of the implementation details. They should just be able to `import foo` then start calling `foo.bar(a)` on anything array-like, with sensible dispatching to either the numpy or dask backend depending on the type of `a`, with both backends automatically registered and ready to use on import.

For 0.1% of users they might want some manual control over which backend to use. E.g., they might want to use the dask backend on a numpy array. But this is a minority of power users, and they could probably figure out that they could do `foo.bar(da.from_array(a))` to control the dispatch path. I.e., I'm not sure I need to be able to "switch backends" completely.

Apologies if this is out of scope, but thought it might be relevant to share some thoughts.

**Comment by rgommers** [comment]
> The blog post is very useful, I think uarray is close to what I'm after. It is probably lack of sleep but I am still struggling to grok the API. 

@hameerabbasi just expanded the blog post with more complete examples, hopefully that helps.

> Multiple dispatch is easier to grok and to use, but I get that uarray is trying to do more than just multiple dispatch. I'm currently trying to figure out if using multiple dispatch is the best approach for my use case, or if uarray provides some additional benefits that are worth the extra complexity.

Yes, `multipledispatch` is nice too. I'd think the single largest  difference is indeed that `multipledispatch` dispatches on types of the inputs, so you can only have one implementation for a given type. So for `f(x)` where `x` is a `numpy.ndarray`, there's only one implementation possible. 

Either way, I'd be interested in the outcome of your comparison. I'm sure that each library has its own set of use cases for which its the best fit; being able to describe those in the docs would help users decide.
