### ISSUE TITLE
Measure uarray overhead and improve it

### ISSUE THREAD

**Issue by rgommers** [Quansight-Labs/uarray#156]
Uarray overhead is currently on the order of 100 us. This is too high - it will prevent adoption as the tool to define one's main API for many use cases.

Would be good to be able to measure the overhead easily:
- test setup
- benchmarks

And then bring it down to a more reasonable level. What is possible without removing functionality? What is the most expensive part of the current design?

**Comment by grlee77** [comment]
Thanks for opening this @rgommers.
 
When I looked at this briefly a few days ago, it seemed that the following few lines currently account for the majority of the overhead (as determined using `spyder-line-profiler`):
https://github.com/Quansight-Labs/uarray/blob/c6ab8022213f7fa7e6b576db49bae69da6cd515b/uarray/backend.py#L281-L284

**Comment by rgommers** [comment]
That one line using `inspect` was commented out in gh-157. With a 15x speedup. Overhead now 2 us according to the measurement in that PR. 

On my machine, the overhead of a Python function call is 65 ns, and that of a numpy ufunc 400 ns. In that light, I think 2 us is acceptable, 15x more not. 

Keeping in mind that everything in this repo is still pure Python and can be sped up further by moving to C, I think the current status is OK for use in `scipy.fft`.

Do you agree @grlee77?

**Comment by grlee77** [comment]
Yeah, 2 us is much more reasonable and should negligible compared to most FFT execution times. Even a fairly small 2D FFT of size (256, 256) takes ~ 200 us with pyFFTW on my system.

**Comment by grlee77** [comment]
Great job @peterbell10 and @hameerabbasi !

For reference, on a recent Linux machine (Intel(R) Core(TM) i9-7900X CPU) with Python 3.7:

commit c6ab802:  **31.3 us**   (prior to the optimizations)
just prior to merge of Peter's C++ PR:  **2.82 us**
after merge of Peter's C++ PR:  **1.06 us**
direct call to numpy.zeros:  **422 ns**

I get only slightly slower timings on an OS X macbook. On another, much older Linux workstation. all overheads are a factor of 3-5 times higher, but the trends are the same.

I used the following in IPython to get the times above:


```python
import numpy as np
import uarray as ua
import unumpy as unp
from unumpy import numpy_backend

with ua.set_backend(numpy_backend):
    %timeit unp.zeros(16)

%timeit np.zeros(16)
```

**Comment by rgommers** [comment]
> Great job @peterbell10 and @hameerabbasi !

Seconded, this is awesome!
