### ISSUE TITLE
Document the uarray API

### ISSUE THREAD

**Issue by rgommers** [Quansight-Labs/uarray#159]
After seeing on the scipy-dev mailing list that the API had changed significantly (now based on a protocol), I tried to understand the new API from https://uarray.readthedocs.io/en/latest/generated/uarray.html. That didn't help me. It needs a rewrite.

It should probably start with: what API does it allow offering to the **end user**?
- `set_backend` or `use_backend` (unclear which one, or both, right now)
- `set_global_backend` (is this for a user?)
- `from .... import libname_backend`
- anything else? (`BackendNotImplementedError`, other warnings/errors, does an end user import `uarray` or from somewhere else, etc.)

Then, what is the API for a **backend author**:
- function to register a backend
- `skip_backend`
- `__ua_domain__` and `__ua_function__` (is this for backend authors too?)
- `__ua_convert__` ?
- ...?

Finally, what is the API for a **library author** wanting to implement a backend system for her API?:
- `create_multimethod` / `generate_multimethod` (are both needed? if so, what is the difference?)
- `Dispatchable`
- `mark_as` (what's this?)
- ....

Another section that seems needed is _Concepts_. What are the fundamental concepts here?
- backend
- domain
- multimethod
- protocol
- dispatching
- coercion
- stacklevel (not in docs yet, but needed to explain how to get sane warnings)

**Comment by peterbell10** [comment]
Something else missing from the documentation is what `generate_multimethod`'s default implementation is intended to be.

I had assumed that it would work like: "Try each backend, if none succeed use the default".
But looking at the code, the actual behavior is more like: "Try a backend's `__ua_function__`, then try the default function with the backend exclusively enabled, continue to the next backend".

So, it seems to me that the default is intended to be an implementation in terms of other uarray based functions. Not a complete implementation in it's own right.

**Comment by rgommers** [comment]
> Try each backend, if none succeed use the default

Good point - those kinds of rules should be a separate section of the docs.

**Comment by hameerabbasi** [comment]
> Not a complete implementation in it's own right.

This is possible to do, albeit via trickery. Is first-class support for this needed? If so, I can add it. But adding both a default backend and a set of registered backends is redundant.
