### ISSUE TITLE
Add back the ability to register a backend

### ISSUE THREAD

**Issue by hameerabbasi** [Quansight-Labs/uarray#163]
@peterbell10 As discussed in #159. Important questions:

1. Is both the ability to have a default backend necessary? 
2. Is having multiple registered backends necessary?
3. If only one is needed, which one?
4. Is the order important?

**Comment by peterbell10** [comment]
In our case we want to provide a default implementation for numpy arrays, but we also want users to be able to provide their own backends that is used for numpy arrays instead.

I think that as it currently stands there is no defined ordering so if both of these are installed via `set_global_backend` then it's not guarunteed that the user's backend will be picked. (Is that right?)

**Comment by hameerabbasi** [comment]
> I think that as it currently stands there is no defined ordering so if both of these are installed via set_global_backend then it's not guarunteed that the user's backend will be picked. (Is that right?)

The last person to call `set_global_backend` "wins", in a sense. So, `numpy` would set itself as the default backend via `set_global_backend`, and a user can change it. Unfortunately, we have no way to prevent other libraries from doing this besides a warning in the docs.

**Comment by peterbell10** [comment]
Oh, so you can only have 1 backend at a time now?

**Comment by hameerabbasi** [comment]
What you *can* do is something like `ua.set_backend(be).__enter__()` and that will add it to the list of backends... With the last one being tried first.

**Comment by peterbell10** [comment]
Ah so using `set_backend` you can have multiple backends but there can only be one global backend.

**Comment by hameerabbasi** [comment]
That's correct.

**Comment by hameerabbasi** [comment]
I'm willing to change things around if needed. 🙂

**Comment by hameerabbasi** [comment]
@peterbell10 Is this all satisfactory or are more changes needed?

**Comment by peterbell10** [comment]
My main concern is that `set_global_backend` doesn't allow for the system to fallback on a default implementation when missing from the backend. For reference, some of this was discussed in https://github.com/scipy/scipy/issues/10175#issuecomment-492024426. 

Although, I suppose I could wrap the specific backend in a way that handles this fallback case.

**Comment by hameerabbasi** [comment]
Ah, yes, I see what you mean... Registering multiple global backends becomes necessary then. I'll switch to that.

**Comment by hameerabbasi** [comment]
Done in #160.
