### ISSUE TITLE
Behavior when __ua_convert__ returns NotImplemented

### ISSUE THREAD

**Issue by peterbell10** [Quansight-Labs/uarray#165]
What does a result of `NotImplemented` from `__ua_convert__` mean? 

I expected that this meant the backend cannot convert the type to something it understands. Thus, there is no point calling the backend's `__ua_function__` and instead we should just try the next backend. This would be similar to `__ua_function__` returning `NotImplemented`.

The actual behaviour is that the value is passed to the `argument_replacer` as normal but not passed to `__ua_function__`'s list of `dispatchable_args`.

Is there some reasoning that I'm missing?

**Comment by hameerabbasi** [comment]
Ah, this is a bug... `NotImplemented` was originally supposed to signal "don't convert me at all", but it can be changed to "I don't know how to handle this".
