### ISSUE TITLE
Non-coercible Dispatchables

### ISSUE THREAD

**Issue by peterbell10** [Quansight-Labs/uarray#166]
An observation based on the `unumpy` code
https://github.com/Quansight-Labs/uarray/blob/1fc6b68cbfbac12b6ff041a6a1a584feeaa8d2a8/unumpy/multimethods.py#L335-L338

If the `out` parameter is coerced to another type, then the result is not going to be written into the `out` param at all.

I think that either: `out` shouldn't really be a `Dispatchable`, or there needs to be some way of marking the parameter as non-coercible.

**Comment by hameerabbasi** [comment]
> there needs to be some way of marking the parameter as non-coercible.

Done in #160.
