### ISSUE TITLE
Functions taking **kwargs

### ISSUE THREAD

**Issue by peterbell10** [Quansight-Labs/uarray#171]
uarray does not support funtions taking arbitrary keyword arguments because of this line:
https://github.com/Quansight-Labs/uarray/blob/619e12000561b702fbbf7f228b0ce353a907af6f/uarray/_backend.py#L138
This silently drops any unknown keyword arguments. 

As far as I can tell, the main motivation for this is to support cases where `argument_replacer` returns extra keyword arguments as is the case with 
https://github.com/Quansight-Labs/uarray/blob/619e12000561b702fbbf7f228b0ce353a907af6f/unumpy/multimethods.py#L28-L33
which (as I found out in #170) is used with functions where `dtype` is not a valid kwarg.

**Comment by peterbell10** [comment]
Why was this closed?

**Comment by hameerabbasi** [comment]
I committed to master with a magic comment that fixed this issue. 😄

**Comment by peterbell10** [comment]
Ah, I see. Thanks!
