### ISSUE TITLE
add a method to clear registered and/or global backends

### ISSUE THREAD

**Issue by grlee77** [Quansight-Labs/uarray#181]
from the discussion in scipy/scipy#10383

>   should there be a mechanism to clear registered backends and/or the global backend?

**Comment by hameerabbasi** [comment]
I kind of feel if someone _really_ wants to clear a backend, they should be using the context manager.

Given that, it's useful for debugging in case there are too many backends set. Perhaps add it with a warning in the docs that "only use this for debugging, if you need a temporary backend use the context manager instead"?
