### ISSUE TITLE
Documentation builds are failing

### ISSUE THREAD

**Issue by hameerabbasi** [Quansight-Labs/uarray#182]
https://readthedocs.org/projects/uarray/builds/9371849/

**Comment by peterbell10** [comment]
>ImportError: cannot import name '_uarray' from 'uarray' (/home/docs/checkouts/readthedocs.org/user_builds/uarray/checkouts/latest/uarray/__init__.py)

It's trying to build the docs without building the extension first.

**Comment by hameerabbasi** [comment]
It does, that's what confuses me:

```
Successfully installed Pygments-2.4.2 doc8-0.8.0 pbr-5.4.0 restructuredtext-lint-1.3.0 sphinx-2.1.2 sphinxcontrib-applehelp-1.0.1 sphinxcontrib-devhelp-1.0.1 sphinxcontrib-htmlhelp-1.0.2 sphinxcontrib-jsmath-1.0.1 sphinxcontrib-qthelp-1.0.2 sphinxcontrib-serializinghtml-1.1.3 stevedore-1.30.1 uarray-0+untagged.131.g8abeec8
```

**Comment by peterbell10** [comment]
Perhaps it's going wrong because it's using the version in the working directory, based on that file path
>`checkouts/latest/uarray/__init__.py`

**Comment by hameerabbasi** [comment]
A `pip install` should make it work regardless of which directory we're in. https://github.com/Quansight-Labs/uarray/blob/8abeec8c54d0e1af98a1cc1babdab9c58278e898/readthedocs.yml#L6

**Comment by peterbell10** [comment]
I think local packages are imported before installed packages. `scipy` at least thinks it's a bad idea

```python
        msg = """Error importing scipy: you cannot import scipy while
        being in scipy source directory; please exit the scipy source
        tree first, and relaunch your python interpreter."""
        raise ImportError(msg)
```

**Comment by hameerabbasi** [comment]
@peterbell10 I think you're right.
cc @rgommers Would you happen to know a fix?

**Comment by rgommers** [comment]
One thing that is weird is that the version name is invalid: `uarray==0+untagged.131.g8abeec8`. This should be something like `uarray-0.5.0.dev0+g8abeec8`. 

It's still failing. Wheel does seem to be built and correctly installed:
```
Building wheels for collected packages: uarray
  Building wheel for uarray (setup.py): started
  Building wheel for uarray (setup.py): finished with status 'done'
  Stored in directory: /tmp/pip-ephem-wheel-cache-7dpwz2hi/wheels/63/c8/73/0fceac24bbecad0af567c4b972b62401a5c6165fe1a31025a4
Successfully built uarray
Installing collected packages: Pygments, sphinx, uarray
  Found existing installation: Pygments 2.3.1
    Uninstalling Pygments-2.3.1:
      Successfully uninstalled Pygments-2.3.1
  Found existing installation: Sphinx 1.8.5
    Uninstalling Sphinx-1.8.5:
      Successfully uninstalled Sphinx-1.8.5
  Found existing installation: uarray 0+untagged.131.g6b696f1
    Uninstalling uarray-0+untagged.131.g6b696f1:
      Successfully uninstalled uarray-0+untagged.131.g6b696f1
Successfully installed Pygments-2.4.2 sphinx-2.1.2 uarray-0+untagged.136.g9e3c1ab
```

You need to turn on verbose mode to see the `uarray` build log though.

**Comment by peterbell10** [comment]
Looks like #185 has fixed this.
https://readthedocs.org/projects/uarray/builds/9374594/
