### ISSUE TITLE
Expose argument extractor and replacer.

### ISSUE THREAD

**Issue by hameerabbasi** [Quansight-Labs/uarray#203]
Argument extractor/replacer may be needed for block-wise and other array-wise operations in many cases. I ran into needing this for Quansight-Labs/unumpy#15

**Comment by peterbell10** [comment]
Can you give an example where this is needed?

**Comment by hameerabbasi** [comment]
Assume a collection of arrays as a duck array, all of the same length `n`, as a duck array. Something like:

```python
class DuckArray(list): # Only holds other duck-arrays.
    pass
```

Now assume an arbitrary function, not a `ufunc`, that has to be applied over multiple `DuckArray` objects, but return a `DuckArray` object of the results.

The way I envision this working is:

```python
def __ua_function__(func, args, kwargs):
    n = []
    d = tuple(func.arg_extractor(*args, **kwargs))
    for i in range(len(d)):
        if d.type is np.ndarray
            n.append(i)

    if len(n) == 0:
        with ua.skip_backend(sys.modules[__name__]):
            return func(*args, **kwargs)
    
    len_duckarray = len(n[0])

    res = DuckArray()

    for n_j in [[n[j][i] for j in range(len(n))] for i in range(len(n[0]))]:
        d_j = []
        for i in range(len(d)):
            d_j.append(ua.Dispatchable(n_j[i], np.ndarray) if d[i].type is np.ndarray else d[j])
        a, kw = func.arg_replacer(a, kw, d_j)
        res.append(func(*a, **kw))
    return res
```

I'd be glad to have a simpler method!

**Comment by peterbell10** [comment]
Will that method not break with `out` parameters?

**Comment by hameerabbasi** [comment]
Surprisingly no, since it writes to the original object, it'll write to the correct arrays. However, it will return the wrong one.

**Comment by peterbell10** [comment]
I'm a little sceptical because it seems to me that this is solving a very different problem from `__ua_convert__`. In the convert protocol we don't know what types the user will have passed into the function; for `__ua_function__` the arguments should already have type `DuckArray` so a simple `isinstance` check should be enough. i.e.

```python
def __ua_function__(func, args, kwargs):
	for a in itertools.chain(args, kwargs.values()):
		if isinstance(a, DuckArray):
			len_duckarray = len(a)
			break
	else:
		with ua.skip_backend(sys.modules[__name__]):
            return func(*args, **kwargs)

	res = DuckArray()
	for i in range(len_duckarray):
	    a_i = [a[i] if isinstance(a, DuckArray) else a for a in args]
		k_i = {k:(v[i] if isinstance(v, DuckArray) else v) for k, v in kwargs}
		
		res.append(func(*a_i, **kw_i))

	return res
```

**Comment by hameerabbasi** [comment]
This doesn't work for nested things like `concatenate` and `block`.
