### ISSUE TITLE
Issues with nested context manager when using cached object

### ISSUE THREAD

**Issue by hameerabbasi** [Quansight-Labs/uarray#206]
Reproducer:

```python
class Backend:
    __ua_domain__ = "ua_bug"

    @staticmethod
    @ua.wrap_single_convertor
    def __ua_convert__(value, dispatch_type, coerce):
        return value

    @staticmethod
    def __ua_function__(func, args, kwargs):
        pass

# Should just create the context manager, not set the backend
be = ua.set_backend(Backend)


with be:
    with be:
        pass
```

Error message:

```
Traceback (most recent call last):
     ...
RuntimeError: Found invalid context state while in __exit__
```

**Comment by hameerabbasi** [comment]
I think the bug can be safely fixed by removing these lines:
https://github.com/Quansight-Labs/uarray/blob/ddbdad8bec3c94258e646313bcb20189f103a120/uarray/_uarray_dispatch.cxx#L317-L319

**Comment by hameerabbasi** [comment]
With additional checks to see if we're not resizing to a size less than zero.

**Comment by peterbell10** [comment]
Stated another way: the context managers aren't [reentrant](http://www.chiark.greenend.org.uk/doc/python3/html/library/contextlib.html#reentrant-context-managers).

I don't understand why this a problem and the support in #207 makes the code quite a bit more complicated. Is there any benefit to using reentrancy over just calling `set_backend` twice?

**Comment by hameerabbasi** [comment]
### Benchmarks
#### Case 1
```
with ua.set_backend(Backend):
    pass
```

#### Case 2:
```
with ctx:
    pass
```

### `master`
Case 1: 338 ns ± 5.84 ns
Case 2: 86.6 ns ± 0.847

### `fix-nested`
Case 1: 392 ns ± 3.06 ns
Case 2: 85.1 ns ± 1.06 ns

**Comment by peterbell10** [comment]
So this does pessimise `set_backend` a bit (~50 ns). But the performance overhead of object creation is already quite high (~240 ns). I think for built in types (e.g. `PyTuple`) CPython uses a free-list to mitigate this issue.

I think (ideally) calls to `set_backend` would be cheap enough that users don't need to worry about this. So, should I try to bring down the cost of `set_backend`?

**Comment by hameerabbasi** [comment]
> So, should I try to bring down the cost of `set_backend`?

This would be useful for meta-arrays that frequently need `skip_backend`/`set_backend` inside themselves, but I'm not sure how much it would add to the code complexity or maintenance burdens. I think caching is probably okay, given we can recommend it in the docs, and it would be hard to beat anyway.

**Comment by peterbell10** [comment]
One idea would be to have a global cache of context manager objects and set_backend would return the global singleton value. This would also require reentrancy but we don't pessimise set_backend in the same way.

**Comment by hameerabbasi** [comment]
I thought of the same thing, but that has the danger of memory leaks, if for example, someone uses a backend factory or similar.

**Comment by peterbell10** [comment]
That could be fixed using weak references.

**Comment by hameerabbasi** [comment]
If that's fixable, I'm all for doing that!
