### ISSUE TITLE
Improve context manager performance

### ISSUE THREAD

**Issue by peterbell10** [Quansight-Labs/uarray#208]
As per the discussion in https://github.com/Quansight-Labs/uarray/issues/206#issuecomment-535482750, `with ua.set_backend(be)` (and all other context managers) has a cost of ~400 ns.

This could be improved by e.g. having a global cache of `SetBackendContext` objects. Such a cache would need to use weak references to avoid leaking backend instances.

**Comment by hameerabbasi** [comment]
Implementing this is turning out to be more complicated than I thought. Since `tuple` objects do not support weak references, we need to create an object in order to implement the `set_backend` weak reference. Which destroys the point of the speedup either way.
