### ISSUE TITLE
Overlap with egison

### ISSUE THREAD

**Issue by saulshanabrook** [Quansight-Labs/uarray#21]
As I was looking into translating einsum notation into MoA (https://github.com/Quansight-Labs/uarray/issues/17), I came across a very recent paper by @egisatoshi called ["Scalar and Tensor Parameters for Importing the Notation in Differential Geometry into Programming"](https://arxiv.org/abs/1804.03140). 

Interestingly, he has also been working on similar types of pattern matching methods that we are using (see ["Non-linear Pattern Matching with Backtracking for Non-free Data Types"](https://www.semanticscholar.org/paper/Non-linear-Pattern-Matching-with-Backtracking-for-Egi-Nishiwaki/4280fbed17d558b6c7228bef405a41a2f063db30)).

He is also developing the [Egison programming language](https://github.com/egison/egison):

> Egison is a functional programming language featuring its expressive pattern-matching facility. Egison allows users to define efficient and expressive pattern-matching methods for arbitrary user-defined data types including non-free data types such as lists, multisets, sets, trees, graphs, and mathematical expressions. 

Since we seem to be approaching similar areas (array programming) with similar methods (pattern matching), I suspect we could learn from each other.

Also I wonder how Egison's pattern matching differs from Matchpy's (written by @wheerd).

There is a [seperate Ruby library](https://github.com/egison/egison-ruby) that implements Egison pattern matching that looks similar in scope to MatchPy in Python.

**Comment by wheerd** [comment]
@henrik227 is maintaining the Matchpy project now

**Comment by henrik227** [comment]
At a first glance, it looks like Egison doesn't do many-to-one matching. I also saw that they mentioned an infinite number of matches somewhere. I don't know (yet) how that can happen in Egison, but it certainly can't happen in MatchPy.

**Comment by egisatoshi** [comment]
Hi, thank you for your interest in our papers.

In fact, I referred a Matchpy's paper by @wheerd in out pattern-matching paper.
The difference is discussed in Section 3.2 "Extebsible Pattern Matching".

Egison's original feature compared with Matchpy is its customizability.
Egison allows users to define new attributes by themselves using Egison in a concise description.

Egison supports non-linear pattern matching with backtracking but does not do many-to-one matching as @henrik227 mentioned.

**Comment by saulshanabrook** [comment]
Thank you for the overview! [Here](https://arxiv.org/pdf/1808.10603.pdf) is a link to the mentioned paper and a screenshot of the relevant section:

<img width="747" alt="screen shot 2018-11-06 at 2 36 11 pm" src="https://user-images.githubusercontent.com/1186124/48088973-5711d100-e1d1-11e8-9c68-0073477ec795.png">


Closing this for now, since matchpy seems to be filling our needs (thanks @henrik227!) and Egison doesn't have a Python implementation at the moment, so it would require some work to move to it.
