### ISSUE TITLE
DEP: Deprecate `skip_backend`, since it has weird scoping?

### ISSUE THREAD

**Issue by seberg** [Quansight-Labs/uarray#237]
[Within the Dask backend](https://github.com/Quansight-Labs/unumpy/blob/master/unumpy/dask_backend.py#L39) you currently seem to use a `skip_backend` functions. Along the lines of "dangerous complexity", I do not understand why this is necessary.

Within Dask itself, it is known which backend should be used based on the wrapped array-type. Alternatively, I may want to figure out a new wrapped type based on multiple Dask arrays (wrapping different types).
But: I probably *never* want a random outer-scope setting opt me into working with cupy arrays locally when the chunk type is NumPy. Rather than using `skip_backend` this should thus be an explicit `set_backend` or maybe `determine_backend` if necessary (although I expect that the `determine_backend` can be handled by Dask itself).

As to a default backend for the chunks, it seems that should be an option of the Dask backend and not dependend on the choice for the default array-like outside of dask.

Maybe there are more reasons to have `skip_backend` though.

**Comment by peterbell10** [comment]
>As to a default backend for the chunks, it seems that should be an option of the Dask backend and not dependend on the choice for the default array-like outside of dask.

To be clear, you're suggesting it should be:
```python
with ua.set_backend(dask_backend(chunk_backend=cupy_backend)):
    # ...
```
instead of
```python
with ua.set_backend(dask_backend), ua.set_backend(cupy_backend):
    # ...
```

**Comment by hameerabbasi** [comment]
That's correct, @seberg and I talked offline about this. Also, `dask_backend` should be inside, a mistake I make all the time. 😉

**Comment by seberg** [comment]
Well, I can see one user story in principle. As a way to do a fallback to the "next in line backend" (whatever that means) when a backend does not provide a functionality. But I am not sure that is actually a reasonable use-case...

**Comment by hameerabbasi** [comment]
> Well, I can see one user story in principle. As a way to do a fallback to the "next in line backend" (whatever that means) when a backend does not provide a functionality. But I am not sure that is actually a reasonable use-case...

We already do that if `NotImplemented` is returned.

**Comment by seberg** [comment]
Right, there is no difference of implicit vs. explicit dispatch from the backend perspective.

**Comment by hameerabbasi** [comment]
@rgommers In your experience, how mad would people be if we deprecated this?

**Comment by rgommers** [comment]
Not very I think, the audience for Uarray is still small and its mostly library maintainers that know what to do about deprecations. It's also exposed in `scipy.fft` (http://scipy.github.io/devdocs/reference/fft.html#backend-control) to end users, but I think if regular deprecation cycles are used there it's fine to make changes that improve the package.

**Comment by hameerabbasi** [comment]
Fixed by https://github.com/Quansight-Labs/uarray/commit/8b2ed649f0a486ada741ee5b5a03b9969f573246.
