### ISSUE TITLE
Move to GitHub Actions?

### ISSUE THREAD

**Issue by hameerabbasi** [Quansight-Labs/uarray#259]
Would it be okay to move to GitHub actions for CI and wheel builds?

**Comment by rgommers** [comment]
+1 from me. GitHub Actions is the easiest to work with, and we can steal the `cibuildwheel` setup from scikit-image (Cc @grlee77 who just worked on that - just want to check that's the best thing to copy).

**Comment by grlee77** [comment]
> +1 from me. GitHub Actions is the easiest to work with, and we can steal the cibuildwheel setup from scikit-image (Cc @grlee77 who just worked on that - just want to check that's the best thing to copy).

Yeah, you can potentially refactor to add more things to the matrix and reduce duplication, but it should be a good start. The PyWavelets one is similar, but a little bit simpler (no clang-cl install or OpenMP libs install needed) and has Apple arm64 support. 

Matplotlib and scikit-learn are a couple of other projects using cibuildwheel that can be a useful reference.
