### ISSUE TITLE
CI is broken but silently passing

### ISSUE THREAD

**Issue by rgommers** [Quansight-Labs/uarray#269]
Latest GitHub Actions run ([link](https://github.com/Quansight-Labs/uarray/runs/4998950836?check_suite_focus=true)):

<img width="448" alt="image" src="https://user-images.githubusercontent.com/98330/151933323-76e48ae7-4f7a-4d75-a960-005769e1b634.png">

**Comment by hameerabbasi** [comment]
It seems it was an error fetching the logs from Actions. With your link, I see the following:
![Screenshot 2022-02-01 at 09-23-13 Minor maintenance fixes (#268) · Quansight-Labs uarray aa94c5a ](https://user-images.githubusercontent.com/2190658/151934793-aa88440e-b700-49f2-b313-3da3abea870c.png)

**Comment by rgommers** [comment]
Hmm this is very strange, I am getting the error 3 times in a row in Firefox, but can see the log in Chrome. Ah well, happy it's not broken, closing. Thanks Hameer!

**Comment by hameerabbasi** [comment]
Just a comment -- It may be related to add-ons or caching of some sort. I can see the log fine in Firefox.
