### ISSUE TITLE
Build wheels with Py_LIMITED_API & abi3

### ISSUE THREAD

**Issue by thomasjpfan** [Quansight-Labs/uarray#270]
There are quite a few wheels for [uarray on pypi](https://pypi.org/project/uarray/#files). Given the limited scope of uarray, is it possible to build uarray wheels with `Py_LIMITED_API` on?

Looking at [cryptography on pypi](https://pypi.org/project/cryptography/#files), there are less wheels for most architectures. (pypy still need their own builds)

XREF: https://github.com/pypa/cibuildwheel/issues/78

**Comment by hameerabbasi** [comment]
I believe we use `vectorcall` which is important for speed and not in the limited set.

**Comment by thomasjpfan** [comment]
Ah yes, [PyObject_Vectorcall](https://docs.python.org/3/c-api/call.html#c.PyObject_Vectorcall) and friends are not part of the limited api. Closing issue.
