### ISSUE TITLE
doing a new release including type annotations?

### ISSUE THREAD

**Issue by rgommers** [Quansight-Labs/uarray#276]
@hameerabbasi a release would be helpful to be able to make the new type annotations available. WDYT?

I had a look at the release process, but it's not documented. Based on the GHA file, it may be a matter of:
1. Push a tag `0.9.0`
2. Wait till `build_wheel` is finished, download the artifacts locally, and then upload them to PyPI with `twine`

Is there anything more to it?

**Comment by rgommers** [comment]
thanks @BvB93, that would be great. let's wait till after that is done then.

**Comment by hameerabbasi** [comment]
> @hameerabbasi a release would be helpful to be able to make the new type annotations available. WDYT?
> 
> 
> 
> I had a look at the release process, but it's not documented. Based on the GHA file, it may be a matter of:
> 
> 1. Push a tag `0.9.0`
> 
> 2. Wait till `build_wheel` is finished, download the artifacts locally, and then upload them to PyPI with `twine`
> 
> 
> 
> Is there anything more to it?

I guess wait for and merge the PR for conda-forge and enabling the tag on RTD, but that should be about it.

**Comment by hameerabbasi** [comment]
Just to add: I would also bump the CIBuildWheel version and add macOS universal wheels if possible, also update the supported Python versions. If waiting is feasible I can do this part this weekend.

**Comment by rgommers** [comment]
There already are `universal2` wheels for macOS, and they work fine.

**Comment by hameerabbasi** [comment]
Okay, the Python 3.13rc1 release finally prompted me to push this past the finish line. 0.9.0 should be up on PyPI shortly, uploaded directly using `cibuildwheel`.

**Comment by hameerabbasi** [comment]
0.9.0 somehow didn't want CI to trigger -- 0.9.1 is up on PyPI and conda-forge. I'll make an announcement post soon (tm).
