### ISSUE TITLE
Theano

### ISSUE THREAD

**Issue by saulshanabrook** [Quansight-Labs/uarray#48]
Since Theano is not being actively developed, some people who are using are looking for replacements. If we can have a compatible API with it, then those people can drop in uarray and then target a variety of backends.

**Comment by rgommers** [comment]
I don't think this is worth the effort. There's no easy 1:1 conversion to another library, and it'll be a lot of work. Theano users should just migrate to PyTorch or Tensorflow. 

@saulshanabrook do you mind if we close this?
