### ISSUE TITLE
Draft initial specification of uarray protocol

### ISSUE THREAD

**Issue by dcharbon** [Quansight-Labs/uarray#79]
Draft the initial specification of the class and methods required to implement a uarray backend. Current thinking, we require just these things at minimum:
* Construction of an array
* A method to provide the shape of the array
* A method to provide a specific item from an array
* A method to retrieve the datatype (int, double, etc.) for a dimension?

This will also require adding a mechanism for "generalized ufuncs" or maps.

The specification could consider additional, optional, methods like:
* Retrieving ranges

**Comment by dcharbon** [comment]
@hameerabbasi What would you like to use to draft the specification? I'd like to propose sphinx-doc.

**Comment by hameerabbasi** [comment]
We can do sphinx and throw it up on RTD if that works.

**Comment by hameerabbasi** [comment]
@saulshanabrook Is this better transferred to `metadsl`? Otherwise it's pretty irrelevant, since we're using the NumPy API, providing defaults and (possibly) wrapping things inside a NumPy-compatible wrapper array?

**Comment by saulshanabrook** [comment]
Let's just close it then. We aren't developing a new array API in metadsl either currently.
