### ISSUE TITLE
NumPy Interface

### ISSUE THREAD

**Issue by dhirschfeld** [Quansight-Labs/uarray#8]
I assume you're already well aware but the goals of `uarray` seem similar to [NEP-22](http://www.numpy.org/neps/nep-0022-ndarray-duck-typing-overview.html).

Just opening an issue so that hopefully the communities can work together and align the implementations.

Obligatory xkcd reference 😜 

![](https://imgs.xkcd.com/comics/standards.png)

**Comment by saulshanabrook** [comment]
Yep! I actually think these are tackling slightly different problems and can work well together. I plan on trying out implementing a uarray duck array that conforms to the NumPy API. 


Thanks for opening this.

**Comment by dhirschfeld** [comment]
Thanks for the clarification - I'll be interested to see how things develop!

**Comment by saulshanabrook** [comment]
Just wanted to let you know we have a preliminary implementation of a NumPy duck array: https://github.com/Quansight-Labs/uarray/blob/1ee8fa32389f4ee8d41a43ba5ad2c74f2c7402e0/uarray/uarray/lazy_ndarray.py#L13-L55

Here is an example of using it to to convert numpy code: https://github.com/Quansight-Labs/uarray/blob/master/uarray/NumPy%20Compat.ipynb

We build up an AST in matchpy with the numpy calls, then we compile that back to a python AST currently. But the idea is to make the intermediary form independent of backend, so you can compile the same array algorithm to Python, or to C, or whatever.

**Comment by dhirschfeld** [comment]
I'm wondering if this will be of use in `dask` - especially in relation to their `HighLevelGraph`?

**Comment by dhirschfeld** [comment]
Also, I'm curious if there are any plans to integrate with `ndtypes`? If there would be any benefit to knowing more detailed type information than just `ndim`

**Comment by hameerabbasi** [comment]
Hi @dhirschfeld! I've brought this up in the NumPy mailing list here: http://numpy-discussion.10968.n7.nabble.com/Adding-to-the-non-dispatched-implementation-of-NumPy-methods-td46816.html#a46876

Please feel free to share your thoughts and feedback there.

The reason I waited so long was because I wasn't sure, `uarray` was mature enough or feature-complete enough yet... 😄 

However, `unumpy` still needs to be developed.

**Comment by rgommers** [comment]
> Also, I'm curious if there are any plans to integrate with ndtypes? If there would be any benefit to knowing more detailed type information than just ndim

This didn't get answered until now. Answer is yes - there's an XND backend now, https://github.com/Quansight-Labs/uarray/blob/master/unumpy/xnd_backend.py
