### ISSUE TITLE
Separate into multiple packages

### ISSUE THREAD

**Issue by saulshanabrook** [Quansight-Labs/uarray#93]
Here is a sketch of how we could separate the python packages:

* `uarray`: Core types and dispatching infrastructure
* `umoa`: MoA operations and reductionson them.
* `unumpy`:
  * `ndarray.py`: Lazy numpy ndarray that creates graph. Use `__array_ufunc__` and `__array_function__`
  * `ast.py`: Compile to Python AST of numpy operations. Have default implementations use existing numpy functions
* `unumpy_moa`: Adds `moa` translations for a numpy operations, so we can reduce them (remove intermediates, etc)
* `unumpy_llvm`: Adds `llvmlite` compilations for numpy expressions
* `uscipy_linalg`/ `unumpy_linalg`: Adds scipy or numpy compatible linalg module. Depends on `unumpy` and adds default Python AST versions of linalg functions
* `uscipy_linalg_moa`/ `unumpy_linalg_moa`: Adds moa reductions for linalg

MVP could be, AST creation of a bunch of numpy code, where just one bit is fed through MoA  reductions, rest is compiled to existing numpy operations.

Next one would be same, but in LLVM. This would (I think) be more work.

**Comment by saulshanabrook** [comment]
If we want to have a low level representation of operations, one question is should we try to re-use existing SciPy/NumPy implementations? 

[This](https://github.com/numpy/numpy/blob/1c4ab89870e39be7c4a47258f6d92f532650e5cc/numpy/fft/pocketfft.c#L2229-L2285) seems to be an FFT implementation in NumPy. 

It takes in some `PyObject`, gets a `PyArrayObject` from it, then creates some C struct around the FFT options, and calls `rfft_forward` in a loop. 

The interface here seems to be most obviously `PyObject`, if we wanna re-use this code exactly as is. 

Alternatively, we could write our own wrappers around `rfft_forward` I suppose and pass in the data. If we did this, what would our compatibility layer be? 

i.e. we would need to wrap `rfft_forward` in some function. What should the ABI of the function be?

This is where I *want* to reach for gumath, in that it defines an ABI for array functions. But we need to able to compose those (pretty much arbitrarily, create LLVM code around them). And we can't call an gumath kernel inside of a gumath kernel. So this really limits composition.

**Comment by teoliphant** [comment]
I like this plan.  I think we will need to re-wrap the low-level routines (and modifications to cython and f2py can help us do it).

**Comment by skrah** [comment]
Suppressing looping inside `gumath` would probably require an additional syntax like (just an example, I'm not suggesting that) `noloop... * N * int64`.

Other than that there are no fundamental difficulties.
